#!/bin/sh
### BEGIN INIT INFO
# Provides:          gyrid
# Required-Start:    $local_fs $remote_fs $network $syslog bluetooth
# Required-Stop:     $local_fs $remote_fs $network $syslog bluetooth
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop Gyrid Bluetooth scanner
### END INIT INFO-
#
# This file belongs to Gyrid.
#
# Gyrid is a Bluetooth device scanner.
# Copyright (C) 2009-2012  Roel Huybrechts
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

DAEMON=/usr/share/gyrid/gyrid-start
PIDFILE=/var/run/gyrid.pid
export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

if [ `id -u` -ne 0 ]; then
    echo "You need root privileges to run this script."
    exit 1
fi

. /lib/lsb/init-functions

is_running() {
    if [ `/bin/ps aux | /bin/grep -e ".*python.* $DAEMON" | /bin/grep -v grep | /usr/bin/wc -l` -lt 1 ]; then
        return 1 #FALSE
    else
        return 0 #TRUE
    fi
}

ok_fail() {
    if [ $1 -gt 0 ]; then
        log_end_msg 1
    else
        log_end_msg 0
    fi
}

q_fail() {
    if [ $1 -gt 0 ]; then
        log_end_msg 1
    fi
}

start() {
    log_daemon_msg "Starting Gyrid Bluetooth device scanner" "gyrid"
    if is_running; then
        log_progress_msg "(already running)"
        log_end_msg 0
    else
        start-stop-daemon --start --background --quiet --make-pidfile --pidfile $PIDFILE --exec $DAEMON
        q_fail $?
        sleep 1
        if is_running; then
            log_end_msg 0
        else
            log_end_msg 1
        fi
    fi
}

stop() {
    log_daemon_msg "Stopping Gyrid Bluetooth device scanner" "gyrid"
    if is_running; then
        start-stop-daemon --stop --quiet --retry 30 --pidfile $PIDFILE
        ok_fail $?
    else
        log_progress_msg "(not running)"
        log_end_msg 0
    fi
}

case "$1" in
  start)
    start
	;;
  stop)
    stop
	;;
	restart)
    stop
    start
  ;;
  *)
    echo "Usage: "$1" {start|stop|restart}"
    exit 1
esac

exit 0
