.TH "gyrid" 1
.SH NAME
gyrid \- A Bluetooth device scanner and logger.
.SH SYNOPSIS
.B /etc/init.d/gyrid
start|stop|restart
.SH DESCRIPTION
Gyrid continuously scans the neighborhood for Bluetooth-enabled devices which are publicly visible, given there is a Bluetooth adapter connected. It can scan with multiple adapters simultaneously too.

The MAC-addresses of the discovered devices are saved to a logfile including a timestamp and their device class (which is a number that indicates whether the device is a phone, a carkit, etc.). Optionally, the RSSI value of each detection can be saved as well.

The idea behind this is scientifical. When multiple of these scanners are placed at known positions, the logfiles can be combined into a (geo)database and used for further analysis. This can be done in realtime via a network server or in postprocessing.
.SH OPTIONS
.TP
.B start
Start Gyrid.
.TP
.B stop
Stop Gyrid.
.TP
.B restart
Restart Gyrid.
.SH DEBUG
.B /usr/share/gyrid/gyrid-start debug [--no-log]

To start Gyrid in debug mode, use the gyrid-start script. Debug mode does not daemonize the process and can be ended by issuing Ctrl+C on the console.

Debug mode is more verbose, printing all activity to standard output. This might be useful to spot bugs or issues more easily.

With the optional --no-log flag set, no logs are written to disk.
.SH FILES
.TP
/etc/gyrid.conf
Configuration file where a few options can be specified. The default configuration file documents all options.
.TP
/usr/share/gyrid/blacklist
File where blacklisted MAC-addresses can be listed, which will be exluded from registration. One can list either a full address or only the starting part.
In the latter case, all addresses starting with that part will be blacklisted.
.TP
/var/log/gyrid/
This is the directory where all logfiles are stored.
.SH BUGS
Bugs and patches are welcome via e-mail at <roel.huybrechts@ugent.be>
.SH VCS
Gyrid is maintained in Git at <http://github.com/Roel/Gyrid>. Please test bugs and generate patches against current master.
.SH AUTHOR
Roel Huybrechts <roel.huybrechts@ugent.be>, Ghent University
